name: Lendsqr API Automation
on: [push]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Newman & Allure Reporter
        run: npm install -g newman newman-reporter-allure

      - name: Run API Tests
        continue-on-error: true
        run: |
          newman run collection.json \
          --env-var "token=${{ secrets.ADJUTOR_API_KEY }}" \
          --reporters cli,allure \
          --reporter-allure-export allure-results

      - name: Install Allure CLI
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.24.0/allure-2.24.0.tgz
          tar -zxvf allure-2.24.0.tgz
          sudo mv allure-2.24.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure

      - name: Generate Allure Report
        run: allure generate allure-results --clean -o allure-report

      - name: Deploy Report to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report